In [1]:
print("Hello, World!")
a = 5
b = 10
c = a + b
print(c)

Hello, World!
15

In [2]:
d = 10 
print(c+d)

25

In [3]:
a 
print("LOS REZULTAT")

LOS REZULTAT

In [4]:
b/2

5.0

In [5]:
import pandas as pd
# pyspark -- JAKO SLICAN SINTAKSNO pandasu 
# ALI je tezak za setup i to dodje kao da uzimamo tenk 
# da bismo ubili muhu

# POLARS -- JAKO SLICAN SINTAKSNO pandasu 
import numpy as np

In [6]:
# Dataframe 

df = pd.read_csv("iris.csv")

In [7]:
df.head(3)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [8]:
# df.tail(6)
# df.describe()
# df.info()
# df.columns
# df.index
# df.shape

In [9]:
df['species'] # Series

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: str

In [10]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [11]:
df['petal_length'].value_counts()

petal_length
1.5    14
1.4    12
4.5     8
5.1     8
1.3     7
1.6     7
5.6     6
4.7     5
4.9     5
4.0     5
1.7     4
4.2     4
4.4     4
4.8     4
5.0     4
4.6     3
3.9     3
4.1     3
5.8     3
6.1     3
5.5     3
5.7     3
1.2     2
1.9     2
3.3     2
3.5     2
4.3     2
6.0     2
5.9     2
5.3     2
6.7     2
5.4     2
5.2     2
1.1     1
1.0     1
3.6     1
3.8     1
3.7     1
3.0     1
6.6     1
6.3     1
6.9     1
6.4     1
Name: count, dtype: int64

In [16]:
df.head(101)

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
1             4.9          3.0           1.4          0.2      setosa
2             4.7          3.2           1.3          0.2      setosa
3             4.6          3.1           1.5          0.2      setosa
4             5.0          3.6           1.4          0.2      setosa
..            ...          ...           ...          ...         ...
96            5.7          2.9           4.2          1.3  versicolor
97            6.2          2.9           4.3          1.3  versicolor
98            5.1          2.5           3.0          1.1  versicolor
99            5.7          2.8           4.1          1.3  versicolor
100           6.3          3.3           6.0          2.5   virginica

[101 rows x 5 columns]

In [14]:
import numpy as np
from sklearn.model_selection import train_test_split

In [20]:
X = df.drop('species', axis=1)
# X = df[['petal_length', 'petal_width', 'sepal_length', 'sepal_width']]
y = df['species']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.31, random_state=43)

In [21]:
X_train.head()

    sepal_length  sepal_width  petal_length  petal_width
79           5.7          2.6           3.5          1.0
65           6.7          3.1           4.4          1.4
56           6.3          3.3           4.7          1.6
72           6.3          2.5           4.9          1.5
82           5.8          2.7           3.9          1.2

In [22]:
y_test

30         setosa
0          setosa
138     virginica
67     versicolor
105     virginica
39         setosa
113     virginica
71     versicolor
81     versicolor
57     versicolor
38         setosa
76     versicolor
122     virginica
11         setosa
78     versicolor
97     versicolor
15         setosa
12         setosa
114     virginica
100     virginica
37         setosa
45         setosa
1          setosa
134     virginica
126     virginica
118     virginica
17         setosa
88     versicolor
2          setosa
10         setosa
96     versicolor
19         setosa
93     versicolor
98     versicolor
108     virginica
103     virginica
50     versicolor
120     virginica
62     versicolor
66     versicolor
69     versicolor
142     virginica
80     versicolor
77     versicolor
22         setosa
55     versicolor
90     versicolor
Name: species, dtype: str